### ISSUE TITLE
Remove nested context struct created by Logger.With()

### ISSUE THREAD

**Issue by aaron0browne** [arcus/pkg#12]
This is a consequence of the underlying `zerolog` implementation, but could be problematic if the log messages are read as JSON, because I believe the only the last (or first?) duplicate key will be recognized. Maybe `With` should add the passed fields of context to the underlying logger directly, instead of nesting them in a "context" dict?

Here's the output I'm seeing:

```
{
  "level": "debug",
  "context": {
    "package": "github.com/arcus/cqs/cmd/diff",
    "version": ""
  },
  "context": {
    "config": {
      "debug": true,
      "output": {
        "bucket": "cdc-snapshots-and-diffs-d076ba2ef7e038b1",
        "prefix": "diffs/"
      },
      "input": {
        "prefix": "snapshots/"
      },
      "diff_key": {
        "metadata_key": "diff_key"
      }
    }
  },
  "context": {
    "start_time": 1548429644
  },
  "context": {
    "request": {
      "old": {
        "bucket": "",
        "name": ""
      },
      "new": {
        "bucket": "cdc-snapshots-and-diffs-d076ba2ef7e038b1",
        "name": "diffTestInputs/20190101.csv.gz"
      }
    }
  },
  "context": {
    "output": {
      "summary": {
        "bucket": "cdc-snapshots-and-diffs-d076ba2ef7e038b1",
        "name": "diffs/diffTestInputs/20190101-snapshot-summary.json"
      },
      "diff_events": {
        "bucket": "cdc-snapshots-and-diffs-d076ba2ef7e038b1",
        "name": "diffs/diffTestInputs/20190101-snapshot.ndjson.gz"
      }
    },
    "operation": "snapshot"
  },
  "event": "output names computed",
  "time": 1548429644675407121
}
```

**Comment by bruth** [comment]
> Maybe With should add the passed fields of context to the underlying logger directly, instead of nesting them in a "context" dict?

I believe zerolog includes duplicate keys regardless since it queues and flushes key/value pairs to the output buffer without retaining any memory of what has been logged. This is why its fast/zero alloc, etc. The trade-off it pushing this *merging* of values to the application. In this case fields under the `context` dict.

So the issue here is that multiple chaining of `With` essentially never works as expected since `context` will be repeated. Ugh. One solution without changing the API would be to keep a copy of the context in the logger itself and then include it in every `Info` or `Debug` call. Or to assume `With` includes keys that are expected to not be repeated.

**Comment by aaron0browne** [comment]
> Or to assume `With` includes keys that are expected to not be repeated.

I think this is what I'm suggesting.

**Comment by bruth** [comment]
I agree. Reflecting on this original design, why does `With(...)` imply a nested `context` struct in the first place?

**Comment by aaron0browne** [comment]
> why does `With(...)` imply a nested context struct in the first place?

Not sure 😅
